# The URL the site will be built for
base_url = "https://hoanghl.io/"

minify_html = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    {name = "tags"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# When set to "true", missing highlight languages are treated as errors. Defaults to false.
error_on_missing_highlight = false

# A list of directories used to search for additional `.sublime-syntax` and `.tmTheme` files.
extra_syntaxes_and_themes = []

# The theme to use for code highlighting.
# See below for list of allowed values.
highlight_theme = "material-dark"

[search]
index_format = "elasticlunr_json"

[extra]
show_toc = true
katex_enable = true
katex_auto_render = true
index_page="home"
top_menu = ["home","programming","data-world"]
copyright_string = "Powered by [zola](https://getzola.org/) and [pico](https://github.com/kuznetsov17/pico)."
author = "Hoang Le"
avatar_src = "images/avatar.png"
logo_src = "images/letter.jpg"
nonce=""
description = "Some Description"

[extra.giscus]
data_repo="kuznetsov17/pico"
data_repo_id="R_kgDOLQ4cpw"
data_category="General"
data_category_id="DIC_kwDOLQ4cp84CdIjK"
data_mapping="url"
data_strict="0"
data_reactions_enabled="0"
data_emit_metadata="0"
data_input_position="bottom"
data_lang="en"
crossorigin="anonymous"
src="https://giscus.app/client.js"



[extra.footer.icons]
github = "https://github.com/hoanghl"
linkedin = "https://www.linkedin.com/in/hoanghl/"
